apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-consumer-persistent-volume-claim
  labels:
    app: consumer-order
    tier: backend
  annotations:
    description: "Claim para acessar o volume persistente do microsservi√ßo consumer-order"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
